# [32mINFO    [0m [2022-05-05 14:11:55] test_48999.py        [LINE:45]   {'message': 'Validation Failed', 'errors': ['New branch already exists'], 'documentation_url': 'https://docs.github.com/rest/reference/repos#rename-a-branch'}
# [32mINFO    [0m [2022-05-05 14:11:55] test_48999.py        [LINE:46]   {
    "documentation_url": "https://docs.github.com/rest/reference/repos#rename-a-branch",
    "errors": [
        "New branch already exists"
    ],
    "message": "Validation Failed"
}